/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/config": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Config */
    get: operations["config_api_v1_config_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/brands": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Brands */
    get: operations["brands_api_v1_brands_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/categories": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Categories */
    get: operations["categories_api_v1_categories_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/products": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Products */
    get: operations["products_api_v1_products_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/products/{product_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Product */
    get: operations["product_api_v1_products__product_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/google": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Google Login */
    post: operations["google_login_api_v1_auth_google_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations["logout_api_v1_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/addresses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Addresses */
    get: operations["addresses_api_v1_addresses_get"];
    put?: never;
    /** Create Address */
    post: operations["create_address_api_v1_addresses_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/addresses/{address_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Edit Address */
    put: operations["edit_address_api_v1_addresses__address_id__put"];
    post?: never;
    /** Delete Address */
    delete: operations["delete_address_api_v1_addresses__address_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/favourites": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Favourites */
    get: operations["favourites_api_v1_favourites_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/favourites/{product_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Favourite */
    put: operations["favourite_api_v1_favourites__product_id__put"];
    post?: never;
    /** Unfavourite */
    delete: operations["unfavourite_api_v1_favourites__product_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/checkout/quote": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Quote */
    post: operations["quote_api_v1_checkout_quote_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/orders": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Order List */
    get: operations["order_list_api_v1_orders_get"];
    put?: never;
    /** Place Order */
    post: operations["place_order_api_v1_orders_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/orders/{order_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Order Detail */
    get: operations["order_detail_api_v1_orders__order_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/orders/{order_id}/reorder": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reorder */
    post: operations["reorder_api_v1_orders__order_id__reorder_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/orders/{order_id}/development-payment": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Dev Payment */
    post: operations["dev_payment_api_v1_orders__order_id__development_payment_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Admin Login */
    post: operations["admin_login_api_v1_admin_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Admin Logout */
    post: operations["admin_logout_api_v1_admin_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin Me */
    get: operations["admin_me_api_v1_admin_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/dashboard": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Dashboard */
    get: operations["dashboard_api_v1_admin_dashboard_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/brands": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin Brands */
    get: operations["admin_brands_api_v1_admin_brands_get"];
    put?: never;
    /** Create Brand */
    post: operations["create_brand_api_v1_admin_brands_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/brands/{brand_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Edit Brand */
    put: operations["edit_brand_api_v1_admin_brands__brand_id__put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/categories": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin Categories */
    get: operations["admin_categories_api_v1_admin_categories_get"];
    put?: never;
    /** Create Category */
    post: operations["create_category_api_v1_admin_categories_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/categories/{category_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Edit Category */
    put: operations["edit_category_api_v1_admin_categories__category_id__put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/products": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin Products */
    get: operations["admin_products_api_v1_admin_products_get"];
    put?: never;
    /** Create Product */
    post: operations["create_product_api_v1_admin_products_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/products/{product_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin Product */
    get: operations["admin_product_api_v1_admin_products__product_id__get"];
    /** Edit Product */
    put: operations["edit_product_api_v1_admin_products__product_id__put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/products/{product_id}/variants": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Variant */
    post: operations["create_variant_api_v1_admin_products__product_id__variants_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/products/{product_id}/variants/{variant_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Edit Variant */
    put: operations["edit_variant_api_v1_admin_products__product_id__variants__variant_id__put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/images": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload */
    post: operations["upload_api_v1_admin_images_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/orders": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin Orders */
    get: operations["admin_orders_api_v1_admin_orders_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/orders/{order_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin Order */
    get: operations["admin_order_api_v1_admin_orders__order_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/orders/{order_id}/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Change Status */
    post: operations["change_status_api_v1_admin_orders__order_id__status_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/orders/{order_id}/mark-paid": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mark Paid */
    post: operations["mark_paid_api_v1_admin_orders__order_id__mark_paid_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AddressInput */
    AddressInput: {
      /** Recipient Name */
      recipient_name: string;
      /** Phone */
      phone: string;
      /** Line1 */
      line1: string;
      /** Line2 */
      line2?: string | null;
      /** Landmark */
      landmark?: string | null;
      /** Locality */
      locality?: string | null;
      /** City */
      city: string;
      /** State */
      state: string;
      /** Postal Code */
      postal_code?: string | null;
      /** Latitude */
      latitude?: number | string | null;
      /** Longitude */
      longitude?: number | string | null;
    };
    /** AddressOut */
    AddressOut: {
      /** Recipient Name */
      recipient_name: string;
      /** Phone */
      phone: string;
      /** Line1 */
      line1: string;
      /** Line2 */
      line2?: string | null;
      /** Landmark */
      landmark?: string | null;
      /** Locality */
      locality?: string | null;
      /** City */
      city: string;
      /** State */
      state: string;
      /** Postal Code */
      postal_code?: string | null;
      /** Latitude */
      latitude?: string | null;
      /** Longitude */
      longitude?: string | null;
      /** Id */
      id: number;
    };
    /** Body_upload_api_v1_admin_images_post */
    Body_upload_api_v1_admin_images_post: {
      /** File */
      file: string;
    };
    /** BrandInput */
    BrandInput: {
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /**
       * Active
       * @default true
       */
      active: boolean;
    };
    /** BrandOut */
    BrandOut: {
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /**
       * Active
       * @default true
       */
      active: boolean;
      /** Id */
      id: number;
    };
    /** CartItem */
    CartItem: {
      /** Variant Id */
      variant_id: number;
      /** Quantity */
      quantity: number;
    };
    /** CategoryInput */
    CategoryInput: {
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /**
       * Active
       * @default true
       */
      active: boolean;
      /** Image Url */
      image_url?: string | null;
      /**
       * Display Order
       * @default 0
       */
      display_order: number;
    };
    /** CategoryOut */
    CategoryOut: {
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /**
       * Active
       * @default true
       */
      active: boolean;
      /** Image Url */
      image_url?: string | null;
      /**
       * Display Order
       * @default 0
       */
      display_order: number;
      /** Id */
      id: number;
    };
    /** CheckoutInput */
    CheckoutInput: {
      /** Items */
      items: components["schemas"]["CartItem"][];
      /**
       * Fulfilment Type
       * @enum {string}
       */
      fulfilment_type: "DELIVERY" | "PICKUP";
      /** Address Id */
      address_id?: number | null;
      /**
       * Payment Method
       * @enum {string}
       */
      payment_method: "COD" | "UPI_ON_DELIVERY" | "ONLINE_UPI";
      /** Contact Phone */
      contact_phone?: string | null;
    };
    /** GoogleLoginInput */
    GoogleLoginInput: {
      /** Id Token */
      id_token: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Status
       * @constant
       */
      status: "ok";
    };
    /** ItemOut */
    ItemOut: {
      /** Product Id */
      product_id: number;
      /** Variant Id */
      variant_id: number;
      /** Product Name */
      product_name: string;
      /** Variant Name */
      variant_name: string;
      /** Quantity */
      quantity: number;
      /** Unit Mrp */
      unit_mrp: string;
      /** Unit Selling Price */
      unit_selling_price: string;
      /** Line Total */
      line_total: string;
    };
    /** LoginInput */
    LoginInput: {
      /** Username */
      username: string;
      /** Password */
      password: string;
    };
    /** OrderInput */
    OrderInput: {
      /** Items */
      items: components["schemas"]["CartItem"][];
      /**
       * Fulfilment Type
       * @enum {string}
       */
      fulfilment_type: "DELIVERY" | "PICKUP";
      /** Address Id */
      address_id?: number | null;
      /**
       * Payment Method
       * @enum {string}
       */
      payment_method: "COD" | "UPI_ON_DELIVERY" | "ONLINE_UPI";
      /** Contact Phone */
      contact_phone?: string | null;
      /** Quote Token */
      quote_token: string;
      /** Idempotency Key */
      idempotency_key: string;
    };
    /** OrderOut */
    OrderOut: {
      /** Id */
      id: number;
      /** Order Number */
      order_number: string;
      /** Customer Phone */
      customer_phone: string;
      /** Fulfilment Type */
      fulfilment_type: string;
      /** Status */
      status: string;
      /** Payment Method */
      payment_method: string;
      /** Payment Status */
      payment_status: string;
      /** Subtotal */
      subtotal: string;
      /** Delivery Fee */
      delivery_fee: string;
      /** Discount */
      discount: string;
      /** Total */
      total: string;
      /** Address Snapshot */
      address_snapshot: {
        [key: string]: unknown;
      } | null;
      /** Cancellation Reason */
      cancellation_reason: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Items */
      items: components["schemas"]["ItemOut"][];
      /** Payment Attempts */
      payment_attempts: components["schemas"]["PaymentOut"][];
    };
    /** PaymentOut */
    PaymentOut: {
      /** Id */
      id: number;
      /** Provider */
      provider: string;
      /** Reference */
      reference: string;
      /** Status */
      status: string;
      /** Amount */
      amount: string;
    };
    /** ProductInput */
    ProductInput: {
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /**
       * Active
       * @default true
       */
      active: boolean;
      /** Image Url */
      image_url?: string | null;
      /** Brand Id */
      brand_id: number;
      /**
       * Description
       * @default
       */
      description: string;
      /**
       * Available
       * @default true
       */
      available: boolean;
      /** Category Ids */
      category_ids?: number[];
    };
    /** ProductOut */
    ProductOut: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /** Description */
      description: string;
      /** Image Url */
      image_url: string | null;
      /** Active */
      active: boolean;
      /** Available */
      available: boolean;
      /** Brand Id */
      brand_id: number;
      brand: components["schemas"]["BrandOut"];
      /** Categories */
      categories: components["schemas"]["CategoryOut"][];
      /** Variants */
      variants: components["schemas"]["VariantOut"][];
    };
    /** ProductPage */
    ProductPage: {
      /** Items */
      items: components["schemas"]["ProductOut"][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
    };
    /** QuoteOut */
    QuoteOut: {
      /** Items */
      items: components["schemas"]["ItemOut"][];
      /** Subtotal */
      subtotal: string;
      /** Delivery Fee */
      delivery_fee: string;
      /** Discount */
      discount: string;
      /** Total */
      total: string;
      /** Address Snapshot */
      address_snapshot: {
        [key: string]: unknown;
      } | null;
      /** Quote Token */
      quote_token: string;
      /**
       * Expires In
       * @default 600
       */
      expires_in: number;
    };
    /** ReorderOut */
    ReorderOut: {
      /** Items */
      items: components["schemas"]["CartItem"][];
      /** Products */
      products: components["schemas"]["ProductOut"][];
      /** Unavailable */
      unavailable: string[];
    };
    /** TokenResponse */
    TokenResponse: {
      /** Token */
      token: string;
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string;
    };
    /** TransitionInput */
    TransitionInput: {
      /**
       * Status
       * @enum {string}
       */
      status: "ACCEPTED" | "OUT_FOR_DELIVERY" | "DELIVERED" | "CANCELLED";
      /** Reason */
      reason?: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** VariantInput */
    VariantInput: {
      /** Name */
      name: string;
      /** Mrp */
      mrp: number | string;
      /** Selling Price */
      selling_price: number | string;
      /**
       * Active
       * @default true
       */
      active: boolean;
      /**
       * Available
       * @default true
       */
      available: boolean;
      /**
       * Display Order
       * @default 0
       */
      display_order: number;
    };
    /** VariantOut */
    VariantOut: {
      /** Name */
      name: string;
      /** Mrp */
      mrp: string;
      /** Selling Price */
      selling_price: string;
      /**
       * Active
       * @default true
       */
      active: boolean;
      /**
       * Available
       * @default true
       */
      available: boolean;
      /**
       * Display Order
       * @default 0
       */
      display_order: number;
      /** Id */
      id: number;
      /** Product Id */
      product_id: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  config_api_v1_config_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  brands_api_v1_brands_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BrandOut"][];
        };
      };
    };
  };
  categories_api_v1_categories_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CategoryOut"][];
        };
      };
    };
  };
  products_api_v1_products_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
        q?: string | null;
        category_id?: number | null;
        available?: boolean | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductPage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  product_api_v1_products__product_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  google_login_api_v1_auth_google_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GoogleLoginInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  addresses_api_v1_addresses_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AddressOut"][];
        };
      };
    };
  };
  create_address_api_v1_addresses_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddressInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AddressOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  edit_address_api_v1_addresses__address_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        address_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddressInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AddressOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_address_api_v1_addresses__address_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        address_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  favourites_api_v1_favourites_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductOut"][];
        };
      };
    };
  };
  favourite_api_v1_favourites__product_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  unfavourite_api_v1_favourites__product_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  quote_api_v1_checkout_quote_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CheckoutInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QuoteOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  order_list_api_v1_orders_get: {
    parameters: {
      query?: {
        page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrderOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  place_order_api_v1_orders_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrderInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrderOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  order_detail_api_v1_orders__order_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        order_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrderOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reorder_api_v1_orders__order_id__reorder_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        order_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReorderOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  dev_payment_api_v1_orders__order_id__development_payment_post: {
    parameters: {
      query: {
        outcome: "PAID" | "FAILED";
      };
      header?: never;
      path: {
        order_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrderOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  admin_login_api_v1_admin_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  admin_logout_api_v1_admin_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  admin_me_api_v1_admin_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  dashboard_api_v1_admin_dashboard_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  admin_brands_api_v1_admin_brands_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BrandOut"][];
        };
      };
    };
  };
  create_brand_api_v1_admin_brands_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BrandInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BrandOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  edit_brand_api_v1_admin_brands__brand_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        brand_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BrandInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BrandOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  admin_categories_api_v1_admin_categories_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CategoryOut"][];
        };
      };
    };
  };
  create_category_api_v1_admin_categories_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CategoryInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CategoryOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  edit_category_api_v1_admin_categories__category_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        category_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CategoryInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CategoryOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  admin_products_api_v1_admin_products_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
        q?: string | null;
        category_id?: number | null;
        brand_id?: number | null;
        available?: boolean | null;
        active?: boolean | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductPage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_product_api_v1_admin_products_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  admin_product_api_v1_admin_products__product_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  edit_product_api_v1_admin_products__product_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_variant_api_v1_admin_products__product_id__variants_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VariantInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VariantOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  edit_variant_api_v1_admin_products__product_id__variants__variant_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: number;
        variant_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VariantInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VariantOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  upload_api_v1_admin_images_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_api_v1_admin_images_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  admin_orders_api_v1_admin_orders_get: {
    parameters: {
      query?: {
        page?: number;
        status?:
          | (
              | "PLACED"
              | "ACCEPTED"
              | "OUT_FOR_DELIVERY"
              | "DELIVERED"
              | "CANCELLED"
            )
          | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrderOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  admin_order_api_v1_admin_orders__order_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        order_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrderOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  change_status_api_v1_admin_orders__order_id__status_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        order_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TransitionInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrderOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  mark_paid_api_v1_admin_orders__order_id__mark_paid_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        order_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrderOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
